version: "3"

services:
  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    command: --api.insecure=true --providers.docker --api.dashboard=true
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock